part of 'package:companion_flutter/main.dart';

const _storeIconPath = 'assets/store/icons';

const _bundleProducts = [
  _StoreProduct(
    title: '音乐畅听',
    subtitle: '每月音乐券、无打断收听和专属陪听权益',
    price: 15,
    yearlyPrice: 129,
    kind: _StoreItemKind.musicBundle,
    imageAsset: '$_storeIconPath/headphone_3d.png',
  ),
  _StoreProduct(
    title: '游戏畅玩',
    subtitle: '解锁更多小游戏次数和陪玩互动权益',
    price: 15,
    yearlyPrice: 129,
    kind: _StoreItemKind.gameBundle,
    imageAsset: '$_storeIconPath/video_game_3d.png',
  ),
  _StoreProduct(
    title: '影视畅看',
    subtitle: '电影券与观影陪伴权益组合包',
    price: 25,
    yearlyPrice: 229,
    kind: _StoreItemKind.movieBundle,
    imageAsset: '$_storeIconPath/clapper_board_3d.png',
  ),
];

const _exchangeProducts = [
  _StoreProduct(
    title: '奶茶',
    subtitle: '每日限购 0/1',
    price: 99,
    kind: _StoreItemKind.tea,
    category: _ExchangeCategory.gift,
    imageAsset: '$_storeIconPath/bubble_tea_3d.png',
  ),
  _StoreProduct(
    title: '提拉米苏',
    subtitle: '每日限购 0/1',
    price: 99,
    kind: _StoreItemKind.cake,
    category: _ExchangeCategory.gift,
    badge: '甜品',
    imageAsset: '$_storeIconPath/shortcake_3d.png',
  ),
  _StoreProduct(
    title: '咖啡',
    subtitle: '每日限购 0/1',
    price: 288,
    kind: _StoreItemKind.coffee,
    category: _ExchangeCategory.gift,
    imageAsset: '$_storeIconPath/hot_beverage_3d.png',
  ),
  _StoreProduct(
    title: '可乐',
    subtitle: '每日限购 0/1',
    price: 512,
    kind: _StoreItemKind.cola,
    category: _ExchangeCategory.gift,
    imageAsset: '$_storeIconPath/cup_with_straw_3d.png',
  ),
  _StoreProduct(
    title: '鲜花',
    subtitle: '每日限购 0/1',
    price: 1314,
    kind: _StoreItemKind.flower,
    category: _ExchangeCategory.gift,
    imageAsset: '$_storeIconPath/bouquet_3d.png',
  ),
  _StoreProduct(
    title: '毛绒玩具',
    subtitle: '每周限购 0/1',
    price: 9999,
    kind: _StoreItemKind.plush,
    category: _ExchangeCategory.gift,
    imageAsset: '$_storeIconPath/teddy_bear_3d.png',
  ),
  _StoreProduct(
    title: '胶囊皮肤',
    subtitle: '点击选择样式',
    price: 188,
    kind: _StoreItemKind.capsuleSkin,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeIconPath/gem_stone_3d.png',
  ),
  _StoreProduct(
    title: '聊天框皮肤',
    subtitle: '点击选择样式',
    price: 388,
    kind: _StoreItemKind.chatFrame,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeIconPath/framed_picture_3d.png',
  ),
  _StoreProduct(
    title: '聊天气泡',
    subtitle: '点击选择样式',
    price: 288,
    kind: _StoreItemKind.bubble,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeIconPath/speech_balloon_3d.png',
  ),
  _StoreProduct(
    title: '聊天背景',
    subtitle: '点击选择样式',
    price: 588,
    kind: _StoreItemKind.backdrop,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeIconPath/sunrise_3d.png',
  ),
  _StoreProduct(
    title: '主题皮肤',
    subtitle: '点击选择样式',
    price: 888,
    kind: _StoreItemKind.theme,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeIconPath/artist_palette_3d.png',
  ),
  _StoreProduct(
    title: '信纸皮肤',
    subtitle: '点击选择样式',
    price: 688,
    kind: _StoreItemKind.stationery,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeIconPath/memo_3d.png',
  ),
  _StoreProduct(
    title: '打卡页面皮肤',
    subtitle: '点击选择样式',
    price: 1888,
    kind: _StoreItemKind.checkinSkin,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeIconPath/calendar_3d.png',
  ),
  _StoreProduct(
    title: '补签卡',
    subtitle: '每日限购 0/3',
    price: 100,
    kind: _StoreItemKind.signCard,
    category: _ExchangeCategory.tool,
    imageAsset: '$_storeIconPath/ticket_3d.png',
  ),
  _StoreProduct(
    title: '音乐券',
    subtitle: '每周限购 0/10',
    price: 1888,
    kind: _StoreItemKind.musicCoupon,
    category: _ExchangeCategory.tool,
    imageAsset: '$_storeIconPath/headphone_3d.png',
  ),
  _StoreProduct(
    title: '游戏券',
    subtitle: '每周限购 0/10',
    price: 1888,
    kind: _StoreItemKind.gameCoupon,
    category: _ExchangeCategory.tool,
    imageAsset: '$_storeIconPath/video_game_3d.png',
  ),
  _StoreProduct(
    title: '影视券',
    subtitle: '每周限购 0/10',
    price: 1888,
    kind: _StoreItemKind.movieCoupon,
    category: _ExchangeCategory.tool,
    imageAsset: '$_storeIconPath/clapper_board_3d.png',
  ),
];

const _ticketRechargePacks = [
  _RechargePack(amount: 10, cost: 1, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 80, cost: 8, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 180, cost: 18, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 300, cost: 30, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 980, cost: 98, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 1980, cost: 198, currency: _StoreCurrency.ticket),
];

const _pointRechargePacks = [
  _RechargePack(amount: 10, cost: 1, currency: _StoreCurrency.point),
  _RechargePack(amount: 80, cost: 8, currency: _StoreCurrency.point),
  _RechargePack(amount: 180, cost: 18, currency: _StoreCurrency.point),
  _RechargePack(amount: 300, cost: 30, currency: _StoreCurrency.point),
  _RechargePack(amount: 980, cost: 98, currency: _StoreCurrency.point),
  _RechargePack(amount: 1980, cost: 198, currency: _StoreCurrency.point),
];
