part of 'package:companion_flutter/main.dart';

const _storeGiftPath = 'assets/store/gifts';
const _storeBlindPath = 'assets/store/blinds';
const _storeOutfitPath = 'assets/store/outfits';
const _storeBundlePath = 'assets/store/bundles';
const _musicCouponKind = 'music_hour_coupon';

const _musicBundleTiers = [
  _BundleTier(id: '1', label: '1张', ticketPrice: 10, grantAmount: 1),
  _BundleTier(id: '5', label: '5张', ticketPrice: 45, grantAmount: 5),
  _BundleTier(id: '10', label: '10张', ticketPrice: 80, grantAmount: 10),
];

const _gameBundleTiers = [
  _BundleTier(id: '100', label: '100点', ticketPrice: 20, grantAmount: 100),
  _BundleTier(id: '200', label: '200点', ticketPrice: 35, grantAmount: 200),
  _BundleTier(id: '500', label: '500点', ticketPrice: 80, grantAmount: 500),
];

const _bundleOffers = [
  _BundleOffer(
    kind: _BundleKind.music,
    title: '音乐畅听券',
    subtitle: '1张 = 1小时 AI 音乐陪伴，购买日起 30 天有效',
    imageAsset: '$_storeBundlePath/music.png',
    accent: Color(0xFF20B5FF),
    tiers: _musicBundleTiers,
  ),
  _BundleOffer(
    kind: _BundleKind.game,
    title: '游戏积分券',
    subtitle: '购买后即时发放对应游戏积分',
    imageAsset: '$_storeBundlePath/game.png',
    accent: Color(0xFF6E83FF),
    tiers: _gameBundleTiers,
  ),
  _BundleOffer(
    kind: _BundleKind.vip,
    title: '月度 VIP 体验',
    subtitle: '按月度会员权益发放，账号终身限购 1 次',
    imageAsset: '$_storeBundlePath/vip.png',
    accent: Color(0xFFFFB020),
    yuanPrice: 1,
  ),
];

const _musicCouponProduct = _StoreProduct(
  title: '音乐畅听券',
  subtitle: '30天有效',
  productKind: _musicCouponKind,
  memberPrice: 0,
  listPrice: 0,
  category: _ExchangeCategory.bundle,
  imageAsset: '$_storeBundlePath/music.png',
);

const _exchangeProducts = [
  _StoreProduct(
    title: '美式咖啡',
    subtitle: '饮品',
    productKind: 'gift_1',
    memberPrice: 18,
    listPrice: 25,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/1.png',
  ),
  _StoreProduct(
    title: '单支玫瑰',
    subtitle: '鲜花',
    productKind: 'gift_2',
    memberPrice: 18,
    listPrice: 25,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.flower,
    imageAsset: '$_storeGiftPath/2.png',
  ),
  _StoreProduct(
    title: '拿铁咖啡',
    subtitle: '饮品',
    productKind: 'gift_3',
    memberPrice: 28,
    listPrice: 40,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/3.png',
  ),
  _StoreProduct(
    title: '卡布奇诺',
    subtitle: '饮品',
    productKind: 'gift_4',
    memberPrice: 38,
    listPrice: 55,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/4.png',
  ),
  _StoreProduct(
    title: '毛绒小熊',
    subtitle: '生活',
    productKind: 'gift_5',
    memberPrice: 58,
    listPrice: 85,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/5.png',
  ),
  _StoreProduct(
    title: '抹茶拿铁',
    subtitle: '饮品',
    productKind: 'gift_6',
    memberPrice: 68,
    listPrice: 95,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/6.png',
  ),
  _StoreProduct(
    title: '肥宅快乐水',
    subtitle: '饮品',
    productKind: 'gift_7',
    memberPrice: 68,
    listPrice: 95,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/7.png',
  ),
  _StoreProduct(
    title: '冰红茶',
    subtitle: '饮品',
    productKind: 'gift_8',
    memberPrice: 78,
    listPrice: 110,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/8.png',
  ),
  _StoreProduct(
    title: '蜜桃乌龙茶',
    subtitle: '饮品',
    productKind: 'gift_9',
    memberPrice: 88,
    listPrice: 125,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/9.png',
  ),
  _StoreProduct(
    title: '银质项链',
    subtitle: '饰品',
    productKind: 'gift_10',
    memberPrice: 88,
    listPrice: 125,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/10.png',
  ),
  _StoreProduct(
    title: '玩偶挂件',
    subtitle: '生活',
    productKind: 'gift_11',
    memberPrice: 108,
    listPrice: 155,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/11.png',
  ),
  _StoreProduct(
    title: '柠檬冰茶',
    subtitle: '饮品',
    productKind: 'gift_12',
    memberPrice: 118,
    listPrice: 170,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/12.png',
  ),
  _StoreProduct(
    title: '布朗尼蛋糕',
    subtitle: '美食',
    productKind: 'gift_13',
    memberPrice: 128,
    listPrice: 185,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/13.png',
  ),
  _StoreProduct(
    title: '巧克力曲奇',
    subtitle: '美食',
    productKind: 'gift_14',
    memberPrice: 138,
    listPrice: 195,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/14.png',
  ),
  _StoreProduct(
    title: '芝士蛋糕',
    subtitle: '美食',
    productKind: 'gift_15',
    memberPrice: 148,
    listPrice: 210,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/15.png',
  ),
  _StoreProduct(
    title: '特调鸡尾酒',
    subtitle: '饮品',
    productKind: 'gift_16',
    memberPrice: 158,
    listPrice: 225,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/16.png',
  ),
  _StoreProduct(
    title: '精酿啤酒',
    subtitle: '饮品',
    productKind: 'gift_17',
    memberPrice: 168,
    listPrice: 240,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/17.png',
  ),
  _StoreProduct(
    title: '提拉米苏',
    subtitle: '美食',
    productKind: 'gift_18',
    memberPrice: 168,
    listPrice: 240,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/18.png',
  ),
  _StoreProduct(
    title: '奶油蛋糕',
    subtitle: '美食',
    productKind: 'gift_19',
    memberPrice: 178,
    listPrice: 255,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/19.png',
  ),
  _StoreProduct(
    title: '银质手链',
    subtitle: '饰品',
    productKind: 'gift_20',
    memberPrice: 178,
    listPrice: 255,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/20.png',
  ),
  _StoreProduct(
    title: '威士忌',
    subtitle: '饮品',
    productKind: 'gift_21',
    memberPrice: 188,
    listPrice: 270,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.drink,
    imageAsset: '$_storeGiftPath/21.png',
  ),
  _StoreProduct(
    title: '马卡龙',
    subtitle: '美食',
    productKind: 'gift_22',
    memberPrice: 188,
    listPrice: 270,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/22.png',
  ),
  _StoreProduct(
    title: '冰淇淋',
    subtitle: '美食',
    productKind: 'gift_23',
    memberPrice: 218,
    listPrice: 310,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/23.png',
  ),
  _StoreProduct(
    title: '香薰蜡烛',
    subtitle: '生活',
    productKind: 'gift_24',
    memberPrice: 228,
    listPrice: 325,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/24.png',
  ),
  _StoreProduct(
    title: '花香膏',
    subtitle: '生活',
    productKind: 'gift_25',
    memberPrice: 248,
    listPrice: 355,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/25.png',
  ),
  _StoreProduct(
    title: '墨镜',
    subtitle: '配饰',
    productKind: 'gift_26',
    memberPrice: 288,
    listPrice: 410,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.accessory,
    imageAsset: '$_storeGiftPath/26.png',
  ),
  _StoreProduct(
    title: '八音盒',
    subtitle: '生活',
    productKind: 'gift_27',
    memberPrice: 288,
    listPrice: 410,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/27.png',
  ),
  _StoreProduct(
    title: '玫瑰花束',
    subtitle: '鲜花',
    productKind: 'gift_28',
    memberPrice: 288,
    listPrice: 410,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.flower,
    imageAsset: '$_storeGiftPath/28.png',
  ),
  _StoreProduct(
    title: '手摇咖啡机',
    subtitle: '生活',
    productKind: 'gift_29',
    memberPrice: 288,
    listPrice: 410,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/29.png',
  ),
  _StoreProduct(
    title: '多肉盆栽',
    subtitle: '饰品',
    productKind: 'gift_30',
    memberPrice: 308,
    listPrice: 440,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/30.png',
  ),
  _StoreProduct(
    title: '水晶手串',
    subtitle: '饰品',
    productKind: 'gift_31',
    memberPrice: 328,
    listPrice: 470,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/31.png',
  ),
  _StoreProduct(
    title: '头戴耳机',
    subtitle: '数码',
    productKind: 'gift_32',
    memberPrice: 328,
    listPrice: 470,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.digital,
    imageAsset: '$_storeGiftPath/32.png',
  ),
  _StoreProduct(
    title: '康乃馨花束',
    subtitle: '鲜花',
    productKind: 'gift_33',
    memberPrice: 328,
    listPrice: 470,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.flower,
    imageAsset: '$_storeGiftPath/33.png',
  ),
  _StoreProduct(
    title: '针织围巾',
    subtitle: '配饰',
    productKind: 'gift_34',
    memberPrice: 388,
    listPrice: 555,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.accessory,
    imageAsset: '$_storeGiftPath/34.png',
  ),
  _StoreProduct(
    title: '郁金香花束',
    subtitle: '鲜花',
    productKind: 'gift_35',
    memberPrice: 388,
    listPrice: 555,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.flower,
    imageAsset: '$_storeGiftPath/35.png',
  ),
  _StoreProduct(
    title: '宝石耳钉',
    subtitle: '饰品',
    productKind: 'gift_36',
    memberPrice: 418,
    listPrice: 595,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/36.png',
  ),
  _StoreProduct(
    title: '满天星花束',
    subtitle: '鲜花',
    productKind: 'gift_37',
    memberPrice: 428,
    listPrice: 610,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.flower,
    imageAsset: '$_storeGiftPath/37.png',
  ),
  _StoreProduct(
    title: '银质戒指',
    subtitle: '饰品',
    productKind: 'gift_38',
    memberPrice: 468,
    listPrice: 670,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/38.png',
  ),
  _StoreProduct(
    title: '经典香水',
    subtitle: '生活',
    productKind: 'gift_39',
    memberPrice: 488,
    listPrice: 695,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/39.png',
  ),
  _StoreProduct(
    title: '水晶吊坠',
    subtitle: '饰品',
    productKind: 'gift_40',
    memberPrice: 488,
    listPrice: 695,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/40.png',
  ),
  _StoreProduct(
    title: '帆布包',
    subtitle: '配饰',
    productKind: 'gift_41',
    memberPrice: 488,
    listPrice: 695,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.accessory,
    imageAsset: '$_storeGiftPath/41.png',
  ),
  _StoreProduct(
    title: '珍珠耳钉',
    subtitle: '饰品',
    productKind: 'gift_42',
    memberPrice: 548,
    listPrice: 785,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/42.png',
  ),
  _StoreProduct(
    title: '爱心手链',
    subtitle: '饰品',
    productKind: 'gift_43',
    memberPrice: 588,
    listPrice: 840,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/43.png',
  ),
  _StoreProduct(
    title: '蓝牙音箱',
    subtitle: '数码',
    productKind: 'gift_44',
    memberPrice: 588,
    listPrice: 840,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.digital,
    imageAsset: '$_storeGiftPath/44.png',
  ),
  _StoreProduct(
    title: '小香风手提包',
    subtitle: '配饰',
    productKind: 'gift_45',
    memberPrice: 688,
    listPrice: 985,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.accessory,
    imageAsset: '$_storeGiftPath/45.png',
  ),
  _StoreProduct(
    title: '复古双肩包',
    subtitle: '配饰',
    productKind: 'gift_46',
    memberPrice: 688,
    listPrice: 985,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.accessory,
    imageAsset: '$_storeGiftPath/46.png',
  ),
  _StoreProduct(
    title: '滑板',
    subtitle: '生活',
    productKind: 'gift_47',
    memberPrice: 688,
    listPrice: 985,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/47.png',
  ),
  _StoreProduct(
    title: '鼠标',
    subtitle: '数码',
    productKind: 'gift_48',
    memberPrice: 688,
    listPrice: 985,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.digital,
    imageAsset: '$_storeGiftPath/48.png',
  ),
  _StoreProduct(
    title: '球鞋',
    subtitle: '配饰',
    productKind: 'gift_49',
    memberPrice: 788,
    listPrice: 1125,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.accessory,
    imageAsset: '$_storeGiftPath/49.png',
  ),
  _StoreProduct(
    title: '蓝牙耳机',
    subtitle: '数码',
    productKind: 'gift_50',
    memberPrice: 888,
    listPrice: 1270,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.digital,
    imageAsset: '$_storeGiftPath/50.png',
  ),
  _StoreProduct(
    title: '毛绒大玩偶',
    subtitle: '生活',
    productKind: 'gift_51',
    memberPrice: 1588,
    listPrice: 2270,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.life,
    imageAsset: '$_storeGiftPath/51.png',
  ),
  _StoreProduct(
    title: '智能手环',
    subtitle: '数码',
    productKind: 'gift_52',
    memberPrice: 1888,
    listPrice: 2700,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.digital,
    imageAsset: '$_storeGiftPath/52.png',
  ),
  _StoreProduct(
    title: '精致下午茶',
    subtitle: '美食',
    productKind: 'gift_53',
    memberPrice: 1888,
    listPrice: 2700,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/53.png',
  ),
  _StoreProduct(
    title: '豪华大餐一份',
    subtitle: '美食',
    productKind: 'gift_54',
    memberPrice: 2888,
    listPrice: 4200,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.food,
    imageAsset: '$_storeGiftPath/54.png',
  ),
  _StoreProduct(
    title: '游戏机',
    subtitle: '数码',
    productKind: 'gift_55',
    memberPrice: 3888,
    listPrice: 5555,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.digital,
    imageAsset: '$_storeGiftPath/55.png',
  ),
  _StoreProduct(
    title: '钻石戒指',
    subtitle: '饰品',
    productKind: 'gift_56',
    memberPrice: 4888,
    listPrice: 7000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/56.png',
  ),
  _StoreProduct(
    title: '钻石项链',
    subtitle: '饰品',
    productKind: 'gift_57',
    memberPrice: 5888,
    listPrice: 8500,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/57.png',
  ),
  _StoreProduct(
    title: '电脑',
    subtitle: '数码',
    productKind: 'gift_58',
    memberPrice: 6888,
    listPrice: 9900,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.digital,
    imageAsset: '$_storeGiftPath/58.png',
  ),
  _StoreProduct(
    title: '定制礼服',
    subtitle: '配饰',
    productKind: 'gift_60',
    memberPrice: 6888,
    listPrice: 9900,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.accessory,
    imageAsset: '$_storeGiftPath/60.png',
  ),
  _StoreProduct(
    title: '单反相机',
    subtitle: '数码',
    productKind: 'gift_61',
    memberPrice: 7888,
    listPrice: 12000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.digital,
    imageAsset: '$_storeGiftPath/61.png',
  ),
  _StoreProduct(
    title: '名牌包包',
    subtitle: '配饰',
    productKind: 'gift_62',
    memberPrice: 7888,
    listPrice: 12000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.accessory,
    imageAsset: '$_storeGiftPath/62.png',
  ),
  _StoreProduct(
    title: '9999朵玫瑰',
    subtitle: '鲜花',
    productKind: 'gift_59',
    memberPrice: 8888,
    listPrice: 13000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.flower,
    imageAsset: '$_storeGiftPath/59.png',
  ),
  _StoreProduct(
    title: '机械腕表',
    subtitle: '饰品',
    productKind: 'gift_63',
    memberPrice: 9888,
    listPrice: 15000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.jewelry,
    imageAsset: '$_storeGiftPath/63.png',
  ),
  _StoreProduct(
    title: '定制烟火秀',
    subtitle: '奢享',
    productKind: 'gift_64',
    memberPrice: 18888,
    listPrice: 28000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.luxury,
    imageAsset: '$_storeGiftPath/64.png',
  ),
  _StoreProduct(
    title: '花束海洋',
    subtitle: '奢享',
    productKind: 'gift_65',
    memberPrice: 28888,
    listPrice: 42000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.luxury,
    imageAsset: '$_storeGiftPath/65.png',
  ),
  _StoreProduct(
    title: '全城大屏联动',
    subtitle: '奢享',
    productKind: 'gift_66',
    memberPrice: 38888,
    listPrice: 55555,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.luxury,
    imageAsset: '$_storeGiftPath/66.png',
  ),
  _StoreProduct(
    title: '漫天花瓣雨',
    subtitle: '奢享',
    productKind: 'gift_67',
    memberPrice: 48888,
    listPrice: 70000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.luxury,
    imageAsset: '$_storeGiftPath/67.png',
  ),
  _StoreProduct(
    title: '无人机灯光秀',
    subtitle: '奢享',
    productKind: 'gift_68',
    memberPrice: 68888,
    listPrice: 100000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.luxury,
    imageAsset: '$_storeGiftPath/68.png',
  ),
  _StoreProduct(
    title: '星系命名',
    subtitle: '奢享',
    productKind: 'gift_69',
    memberPrice: 99999,
    listPrice: 150000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.luxury,
    imageAsset: '$_storeGiftPath/69.png',
  ),
  _StoreProduct(
    title: '环球奢华游',
    subtitle: '奢享',
    productKind: 'gift_70',
    memberPrice: 666666,
    listPrice: 1000000,
    category: _ExchangeCategory.gift,
    giftSubcategory: _GiftSubcategory.luxury,
    imageAsset: '$_storeGiftPath/70.png',
  ),
  _StoreProduct(
    title: '奶茶盲盒',
    subtitle: '随机开出一份',
    productKind: 'blind_milk_tea',
    memberPrice: 18,
    listPrice: 25,
    category: _ExchangeCategory.blind,
    imageAsset: '$_storeBlindPath/milk_tea.png',
    contents: '珍珠奶茶一杯、波霸奶茶一杯、杨枝甘露一杯、芋泥波波一杯、蜜桃乌龙一杯、桂花乌龙一杯、茉香奶绿一杯、伯爵鲜奶一杯、黑糖珍珠鲜奶一杯、椰奶芋圆一杯、抹茶红豆一杯、焦糖海盐一杯、玫瑰荔枝一杯、蓝莓酸奶一杯、芒果椰奶一杯、草莓脏脏茶一杯、青柠薄荷一杯、百香果双响炮一杯、芝士葡萄一杯、蜜瓜椰奶一杯',
  ),
  _StoreProduct(
    title: '可乐盲盒',
    subtitle: '随机开出一份',
    productKind: 'blind_cola',
    memberPrice: 28,
    listPrice: 40,
    category: _ExchangeCategory.blind,
    imageAsset: '$_storeBlindPath/cola.png',
    contents: '经典可乐一杯、樱桃可乐一杯、香草可乐一杯、青柠可乐一杯、姜汁可乐一杯、肉桂可乐一杯、咖啡可乐一杯、草莓可乐一杯、椰子可乐一杯、蜂蜜可乐一杯',
  ),
  _StoreProduct(
    title: '咖啡盲盒',
    subtitle: '随机开出一份',
    productKind: 'blind_coffee',
    memberPrice: 38,
    listPrice: 55,
    category: _ExchangeCategory.blind,
    imageAsset: '$_storeBlindPath/coffee.png',
    contents: '意式浓缩一杯、美式咖啡一杯、拿铁一杯、卡布奇诺一杯、摩卡一杯、冷萃咖啡一杯、澳白一杯、手冲瑰夏一杯、手冲耶加雪菲一杯、手冲曼特宁一杯、抹茶拿铁一杯、焦糖玛奇朵一杯、海盐拿铁一杯、燕麦拿铁一杯、桂花拿铁一杯、榛果拿铁一杯、香草拿铁一杯、南瓜拿铁一杯、椰青美式一杯、爱尔兰咖啡一杯',
  ),
  _StoreProduct(
    title: '酒精盲盒',
    subtitle: '随机开出一份',
    productKind: 'blind_alcohol',
    memberPrice: 48,
    listPrice: 70,
    category: _ExchangeCategory.blind,
    imageAsset: '$_storeBlindPath/alcohol.png',
    contents: '莫吉托一杯、金汤力一杯、威士忌酸一杯、长岛冰茶一杯、桑格利亚一杯、热红酒一杯、玛格丽特一杯、白俄罗斯一杯、迈泰一杯、贝里尼一杯、浑浊IPA一杯、世涛一杯、比利时三料一杯、水果酸啤一杯、小麦白啤一杯、英式波特一杯、琥珀艾尔一杯、法兰德斯红一杯、赛松一杯、皮尔森一杯',
  ),
  _StoreProduct(
    title: '甜点盲盒',
    subtitle: '随机开出一份',
    productKind: 'blind_dessert',
    memberPrice: 108,
    listPrice: 155,
    category: _ExchangeCategory.blind,
    imageAsset: '$_storeBlindPath/dessert.png',
    contents: '提拉米苏一份、抹茶千层一份、红丝绒蛋糕一份、蓝莓芝士一份、芒果慕斯一份、黑森林蛋糕一份、蒙布朗栗子一份、草莓奶油蛋糕一份、巧克力熔岩一份、椰子冻一份、焦糖布丁一份、半熟芝士一份、可露丽一份、费南雪一份、玛德琳一份、马卡龙一份、蝴蝶酥一份、千层酥一份、闪电泡芙一份、歌剧院蛋糕一份',
  ),
  _StoreProduct(
    title: '鲜花盲盒',
    subtitle: '随机开出一份',
    productKind: 'blind_flower',
    memberPrice: 228,
    listPrice: 330,
    category: _ExchangeCategory.blind,
    imageAsset: '$_storeBlindPath/flower.png',
    contents: '红玫瑰花束一束、粉玫瑰花束一束、白百合花束一束、郁金香花束一束、向日葵花束一束、蓝色绣球花束一束、紫色桔梗花束一束、洋甘菊花束一束、薰衣草花束一束、蝴蝶兰花束一束、白色雏菊花束一束、粉色康乃馨花束一束、香槟玫瑰花束一束、尤加利叶花束一束、雪柳一束、铃兰花束一束、小苍兰花束一束、鸢尾花花束一束、银莲花花束一束、帝王花花束一束',
  ),
  _StoreProduct(
    title: '美食盲盒',
    subtitle: '随机开出一份',
    productKind: 'blind_food',
    memberPrice: 288,
    listPrice: 420,
    category: _ExchangeCategory.blind,
    imageAsset: '$_storeBlindPath/food.png',
    contents: '安格斯牛排券一张、和牛汉堡券一张、秘制炸鸡券一张、麻辣火锅券一张、寿司拼盘券一张、意大利面券一张、披萨券一张、烤羊排券一张、海鲜大餐券一张、泰式冬阴功券一张、日式拉面券一张、越南河粉券一张、西班牙海鲜饭券一张、法式焗蜗牛券一张、烤鸭券一张、钵钵鸡券一张、小龙虾券一张、烤肉拼盘券一张、生蚝刺身券一张、佛跳墙券一张',
  ),
  _StoreProduct(
    title: '胶囊皮肤',
    subtitle: '装扮兑换',
    productKind: 'outfit_capsule',
    memberPrice: 188,
    listPrice: 265,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeOutfitPath/capsule.png',
  ),
  _StoreProduct(
    title: '聊天框皮肤',
    subtitle: '装扮兑换',
    productKind: 'outfit_chat_frame',
    memberPrice: 288,
    listPrice: 405,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeOutfitPath/chat_frame.png',
  ),
  _StoreProduct(
    title: '聊天气泡',
    subtitle: '装扮兑换',
    productKind: 'outfit_bubble',
    memberPrice: 388,
    listPrice: 550,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeOutfitPath/bubble.png',
  ),
  _StoreProduct(
    title: '聊天背景',
    subtitle: '装扮兑换',
    productKind: 'outfit_backdrop',
    memberPrice: 588,
    listPrice: 825,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeOutfitPath/backdrop.png',
  ),
  _StoreProduct(
    title: '主题皮肤',
    subtitle: '装扮兑换',
    productKind: 'outfit_theme',
    memberPrice: 688,
    listPrice: 960,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeOutfitPath/theme.png',
  ),
  _StoreProduct(
    title: '信纸皮肤',
    subtitle: '装扮兑换',
    productKind: 'outfit_stationery',
    memberPrice: 888,
    listPrice: 1240,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeOutfitPath/stationery.png',
  ),
  _StoreProduct(
    title: '打卡页面皮肤',
    subtitle: '装扮兑换',
    productKind: 'outfit_checkin',
    memberPrice: 1888,
    listPrice: 2640,
    category: _ExchangeCategory.outfit,
    imageAsset: '$_storeOutfitPath/checkin.png',
  ),
];

const _ticketRechargePacks = [
  _RechargePack(amount: 10, cost: 1, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 80, cost: 8, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 180, cost: 18, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 300, cost: 30, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 980, cost: 98, currency: _StoreCurrency.ticket),
  _RechargePack(amount: 1980, cost: 198, currency: _StoreCurrency.ticket),
];

const _pointRechargePacks = [
  _RechargePack(amount: 10, cost: 1, currency: _StoreCurrency.point),
  _RechargePack(amount: 80, cost: 8, currency: _StoreCurrency.point),
  _RechargePack(amount: 180, cost: 18, currency: _StoreCurrency.point),
  _RechargePack(amount: 300, cost: 30, currency: _StoreCurrency.point),
  _RechargePack(amount: 980, cost: 98, currency: _StoreCurrency.point),
  _RechargePack(amount: 1980, cost: 198, currency: _StoreCurrency.point),
];

_StoreProduct? _productForKind(String kind) {
  for (final product in _exchangeProducts) {
    if (product.productKind == kind) return product;
  }
  if (kind == _musicCouponKind) return _musicCouponProduct;
  return null;
}
